#!/bin/sh

load_luckfoxconfig() {
	if [ -f /usr/bin/luckfox-config ]; then
		luckfox-config load
		echo "=== Dump board pin diagram ==="
		cat /tmp/.pin_diagram.txt
	fi
	if [ "$(cat /proc/device-tree/model)" == "Luckfox Pico Ultra" ] ||
		[ "$(cat /proc/device-tree/model)" == "Luckfox Pico Ultra W" ]; then
		luckfox_switch_rgb_resolution &
	fi
}

case $1 in
start)
	load_luckfoxconfig
	;;
*)
	exit 1
	;;
esac
